//Howdy! if you're reading this, you're Mr. Unland, or some random twink looking through my shit.
//Rest assured, none of this has been generated by AI. I have painstakingly spent most of my time crafting this code.
//Enjoy, I did a little bit extra than required ;)
//created by Ethan Malka
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        MainContainer inventory = new MainContainer();

        //Setup test environment
        inventory.openBag();
        inventory.addItem(new Weapon("Iron Sword", "A rusty but reliable blade.", 5.0, 12));
        inventory.addItem(new Consumable("Health Potion", "Restores 50 HP.", 1.0, 50));
        inventory.addItem(new Projectile("Arrow", "Wood and feather.", 0.1, 3));
        inventory.addItem(new KeyItem("Brass Key", "Heavy and tarnished.", 0.5));

        boolean running = true;

        while (running) {
            System.out.println("\n--- [1] Search & Use  [2] List Items  [3] Open/Close Bag  [4] Exit ---");
            System.out.print("Action: ");
            String input = scanner.nextLine();

            if (input.equals("1")) {
                System.out.print("Enter item name to use/inspect: ");
                String target = scanner.nextLine();
                Item found = inventory.search(target);

                if (found != null) {
                    found.displayStats();
                    if (found.usable) {
                        boolean consumed = found.use();
                        //Deletes item from memory if the use method flags it as empty/consumed
                        if (consumed) {
                            inventory.removeItem(found);
                        }
                    } else {
                        found.use();
                    }
                } else {
                    System.out.println("Item not found. (Is the bag open?)");
                }
            }
            else if (input.equals("2")) {
                if (inventory.isOpen) {
                    System.out.println("Contents:");
                    for (Item i : inventory.contents) {
                        System.out.println("- " + i.name);
                    }
                } else {
                    System.out.println("Bag is closed.");
                }
            }
            else if (input.equals("3")) {
                if (inventory.isOpen) {
                    inventory.closeBag();
                } else {
                    inventory.openBag();
                }
            }
            else if (input.equals("4")) {
                running = false;
                System.out.println("Exiting inventory...");
            }
            else {
                System.out.println("Invalid command.");
            }
        }
        scanner.close();
    }
}